# Elastic Search Variables
elasticsearch_host: localhost
systemd_src: elastic-timeout.conf

# Kibana Variables
kibana_host: localhost

# Logstash Variables
logstash_conf: logstash.conf

# Nagios Variables
nagios_user: nagiosadmin
nagios_password: password

# LAMP Variables
domain: qigbbravo-tip
owner: qigbbravo-tip
group: qigbbravo-tip
index_html: index.html
ubuntu_src: qigbbravo-tip-ubuntu.conf
centos_src: qigbbravo-tip-centos.conf
